// Grade 7 Coding/CS/AI — Fall Expedition, Week 1 (Back to Basics), Day 5.
// Grade 7 counterpart of g6.fall.code.w1.d5. Same patterns/sequences/rules
// topic, raised to Grade 7: capturing a rule as a FUNCTION with a parameter,
// and tracing/debugging a loop step by step.

export const fallG7CodingW1D5 = {
  id: "g7.fall.code.w1.d5",
  season: "fall",
  gradeLevel: 7,
  weekNumber: 1,
  dayNumber: 5,
  subject: "Coding/Computer Science/AI",
  topic: "Patterns, sequences, and rules as functions",
  topicTag: "patterns-sequences",
  estimatedMinutes: 60, // full Daily Hour
  standardsRefs: ["CSTA.2-AP-11", "CSTA.2-AP-13"],
  hook: "Nature is full of patterns — pinecones, leaf veins, cornfield rows. Coders capture a pattern's RULE as a function: give it an input, get the matching term out. Today you write the rule as a function and trace it like a computer would.",
  miniLesson: [
    "A function is a named rule with a parameter (its input). f(n) = 3n + 2 takes a position n and returns that term: f(1) = 5, f(2) = 8, f(3) = 11.",
    "Writing a pattern as a function beats writing every term: you can jump straight to f(100) without listing the first 99. The parameter is the slot you plug a value into.",
    "To DEBUG, trace the code line by line, tracking each variable's value after every step. If the output is wrong, the trace shows exactly which line changed a value incorrectly."
  ],
  workedExample: {
    prompt: "A leaf-count rule is the function f(n) = 4n − 1, where n is the week number. Trace f(3), then explain what the parameter n does.",
    steps: [
      "Substitute the input into the parameter: replace n with 3.",
      "Compute inside out: 4 × 3 = 12.",
      "Finish the rule: 12 − 1 = 11.",
      "The parameter n is the input slot; changing n gives a different term, so f(3) = 11."
    ],
    answer: "f(3) = 11; the parameter n is the input you plug into the rule to get that term."
  },
  items: [
    {
      id: "g7.fall.code.w1.d5.q1",
      type: "numeric",
      stem: "A sequence rule is the function f(n) = 3n + 2. What is f(5)?",
      answer: 17,
      tolerance: 0,
      unit: "",
      hintLadder: [
        "Substitute 5 in place of the parameter n.",
        "3 × 5 = 15, then add 2.",
        "15 + 2 = 17."
      ],
      explanation: "f(5) = 3 × 5 + 2 = 15 + 2 = 17."
    },
    {
      id: "g7.fall.code.w1.d5.q2",
      type: "multiple_choice",
      stem: "The sequence 5, 8, 11, 14, 17, ... is generated by a function of the position n (starting at n = 1). Which function is correct?",
      choices: [
        "f(n) = 3n + 2",
        "f(n) = 5n",
        "f(n) = n + 3",
        "f(n) = 2n + 3"
      ],
      answerIndex: 0,
      explanation: "The terms go up by 3 each step (so 3n) and f(1) must equal 5, which needs +2: f(n) = 3n + 2. Check: f(1)=5, f(2)=8, f(3)=11.",
      hintLadder: [
        "The constant step (+3 each time) becomes the number multiplied by n.",
        "Now find the '+' amount so that f(1) equals the first term, 5.",
        "3 × 1 = 3, and 3 + 2 = 5, so f(n) = 3n + 2."
      ],
      misconceptionsTargeted: ["confuses-step-with-function"]
    },
    {
      id: "g7.fall.code.w1.d5.q3",
      type: "multiple_choice",
      stem: "A function alternates leaf colors by position: color(n) returns 'red' when n is odd and 'orange' when n is even. What does color(8) return, and why?",
      choices: [
        "'red', because 8 is the last position",
        "'orange', because 8 is even",
        "'red', because odd and even alternate",
        "'orange', because 8 is odd"
      ],
      answerIndex: 1,
      explanation: "The function checks whether the parameter n is even or odd. 8 is even, so color(8) returns 'orange.'",
      hintLadder: [
        "The parameter n is 8 — is it odd or even?",
        "The function returns 'orange' for even inputs.",
        "8 is even, so the output is 'orange.'"
      ]
    },
    {
      id: "g7.fall.code.w1.d5.q4",
      type: "numeric",
      stem: "Trace this loop and give the final value of total:\n  total = 0\n  for i from 1 to 4:\n      total = total + i * 2\nWhat is total after the loop ends?",
      answer: 20,
      tolerance: 0,
      unit: "",
      hintLadder: [
        "Track total after each pass, computing i * 2 first each time.",
        "i=1: total = 0 + 2 = 2; i=2: total = 2 + 4 = 6; i=3: total = 6 + 6 = 12.",
        "i=4: total = 12 + 8 = 20."
      ],
      explanation: "Each pass adds i*2: 2 + 4 + 6 + 8 = 20, so total ends at 20."
    },
    {
      id: "g7.fall.code.w1.d5.q5",
      type: "short_answer",
      stem: "This function is supposed to return the nth square number (1, 4, 9, 16, ...), but it has a BUG:\n  square(n):\n      return n * 2\nExplain what is wrong, trace square(4) as written, and give the corrected function.",
      rubric: {
        level3: "Identifies that n * 2 doubles instead of squaring AND traces square(4) = 8 as written AND corrects it to return n * n (giving 16).",
        level2: "Spots the bug OR gives the correct fix, and traces the wrong output, but not all three parts.",
        level1: "Does not locate the bug or gives an incorrect fix and trace."
      },
      exemplar: "The bug is that n * 2 doubles the input instead of squaring it. As written, square(4) = 4 * 2 = 8, but the 4th square should be 16. The fix is to return n * n (or n squared), so square(4) = 4 * 4 = 16.",
      hintLadder: [
        "Squaring means multiplying a number by itself, not by 2.",
        "Trace square(4) with the buggy line: 4 * 2 = 8 — but the 4th square is 16.",
        "Change n * 2 to n * n so it squares the input."
      ]
    }
  ],
  reflectionPrompt: "Find one pattern in nature near you this week. Could you write its rule as a function f(n) that a friend could plug a position into?",
  misconceptionBank: [
    {
      id: "confuses-step-with-function",
      label: "Uses the step size as the whole function",
      description: "Sees +3 each term and writes f(n) = 3 or f(n) = n + 3 without checking it against the first term.",
      coachMove: "Have them test the candidate function on n = 1: if f(1) doesn't match the first term, adjust the '+' constant until it does."
    },
    {
      id: "assumes-all-patterns-add",
      label: "Assumes every sequence adds a fixed amount",
      description: "Applies an 'add the same number' rule even when the pattern multiplies or squares.",
      coachMove: "Check the step between EVERY pair of terms — if the gap changes, the rule is not simple addition and may need a function like n * n."
    }
  ],
  dailyHour: {
    warmUp: {
      type: "riddle",
      title: "Function Machine Riddle",
      prompt:
        "I am a function machine. You feed me a position n and I return 2n + 1. When you feed me 1, I give 3; feed me 2, I give 5; feed me 3, I give 7. What do I return when you feed me 6?",
      answer: "13 — plug n = 6 into 2n + 1: 2 × 6 + 1 = 13.",
      estimatedMinutes: 5
    },
    creativeLab: {
      title: "Creative Lab: Build a Pattern Function",
      challenge:
        "Coders turn a pattern into a reusable function. Invent a fall-inspired sequence, capture its rule as a function f(n) with a parameter, and prove it works by tracing an input.",
      steps: [
        "Choose a fall-themed sequence (falling leaves, stacked pumpkins, rows of corn).",
        "Write its first five terms, then find the rule as a function f(n) of the position n.",
        "Test your function on n = 1 and n = 2 to confirm it matches your terms.",
        "Hand a friend one input (like n = 7) and check they get the same output your function predicts."
      ],
      deliverable: "A function card: five terms, the function f(n) with its parameter, and a traced check for one input.",
      choiceBoard: [
        "Write a linear function like f(n) = 3n + 1 and trace two inputs.",
        "Write a growing function like f(n) = n * n and show it beats simple addition.",
        "Draw the pattern (dots or leaves) and label each with f(n) beneath it."
      ],
      estimatedMinutes: 15
    },
    challengeArena: {
      title: "Challenge Arena: Function Boss",
      bonusXp: 50,
      estimatedMinutes: 10,
      items: [
        {
          id: "g7.fall.code.w1.d5.arena1",
          type: "numeric",
          stem: "A function is g(n) = n * n − 1. What is g(6)?",
          answer: 35,
          tolerance: 0,
          unit: "",
          hintLadder: [
            "Substitute 6 for the parameter n.",
            "Square first: 6 * 6 = 36.",
            "36 − 1 = 35."
          ],
          explanation: "g(6) = 6 * 6 − 1 = 36 − 1 = 35."
        },
        {
          id: "g7.fall.code.w1.d5.arena2",
          type: "short_answer",
          stem: "This loop should print the total of 2 + 4 + 6 (the first three even numbers) but prints the wrong value:\n  total = 0\n  for i from 1 to 3:\n      total = total + i\n  print(total)\nTrace it, explain the bug, and give the corrected line so it totals the even numbers.",
          rubric: {
            level3: "Traces the buggy loop to total = 6 (1+2+3) AND explains it adds i instead of the even number 2*i AND corrects the line to total = total + i * 2 (giving 12).",
            level2: "Traces the loop OR identifies/fixes the bug, but not all three parts.",
            level1: "No correct trace and no correct fix."
          },
          exemplar: "As written it adds i each pass: 1 + 2 + 3 = 6. The bug is that it adds the position i, not the even number, which is 2 times i. Fixing the line to total = total + i * 2 gives 2 + 4 + 6 = 12.",
          hintLadder: [
            "Trace the current line: total becomes 1, then 3, then 6.",
            "The even number at position i is i * 2, not i.",
            "Change the line to total = total + i * 2 so it sums 2 + 4 + 6 = 12."
          ]
        }
      ]
    },
    moveAndReset: {
      type: "movement",
      title: "Move & Reset: Function Clap-Stomp",
      prompt:
        "Make yourself a function machine: for input n, clap n times then stomp once, for n = 1, 2, 3, 4 in a row — speeding up each round. Your body is running f(n) = 'clap n, stomp 1' for each input!",
      scienceTieIn: "Repeating a rule with a changing input strengthens the brain's sequencing and working-memory circuits — the same thinking that tracing functions and loops in code relies on.",
      estimatedMinutes: 5
    },
    reflectAndReward: {
      journalPrompt:
        "Find one pattern in nature near you this week. Write its rule as a function f(n), then trace one input to show what term it returns.",
      badge: { id: "g7-fall-function-forager", name: "Function Forager", emoji: "🌰" },
      estimatedMinutes: 7
    }
  }
};
